"""delay answer

Revision ID: 230ca8085f77
Revises: d696096e4baf
Create Date: 2024-08-01 21:52:17.979729

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '230ca8085f77'
down_revision: Union[str, None] = 'd696096e4baf'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('post', sa.Column('delay_answer', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('post', 'delay_answer')
    # ### end Alembic commands ###
