"""Autoanswer field was added

Revision ID: 2a737f6490e3
Revises: 73d6dcba8257
Create Date: 2024-07-31 22:36:55.099224

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2a737f6490e3'
down_revision: Union[str, None] = '73d6dcba8257'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('post', sa.Column('auto_answer', sa.Boolean(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('post', 'auto_answer')
    # ### end Alembic commands ###
