version: '3.10'
services:
  backend:
    build:
      context: ./backend/src
      dockerfile: Dockerfile
#    restart: always
    command: >
      /bin/sh -c "
      pytest
      "
    ports:
      - "8001:8000"
    volumes:
      - ./backend/src:/app
    environment:
      - CELERY_BROKER_URL=redis://redis:6379/0
      - CELERY_RESULT_BACKEND=redis://redis:6379/0
    env_file:
      - ./backend/src/.env
    depends_on:
      - database
#      - redis
#      - worker
    extra_hosts:
      - "opti.local.com:host-gateway"

  database:
    image: postgres:15
    restart: always
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_DB=blog_db
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin
    ports:
      - "54322:5432"

#  worker:
#    build: ./backend/src
#    command: celery -A worker.celery worker --loglevel=info
#    volumes:
#      - ./backend/src:/app
#    environment:
#      - CELERY_BROKER_URL=redis://redis:6379/0
#      - CELERY_RESULT_BACKEND=redis://redis:6379/0
#    depends_on:
#      - redis
#
#  redis:
#    image: redis:7

volumes:
    postgres_data:
